Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Plot individual conditional expectations (ICE) with color encoding
explainer.conditional('Latitude').plot(var_color='Longitude', theme='mako').draw()
------------------

----- stderr -----
R callback write-console: the number of evaluation points exceeds the limit: the data is reduced to 1000 observations
----- stderr -----
R callback write-console: Error in get.theme(parsed$name, ifnot.null(parsed$source, source), env) : 
  'mako' is not found in the color theme environment
------------------

[31m---------------------------------------------------------------------------[39m
[31mRRuntimeError[39m                             Traceback (most recent call last)
[36mFile [39m[32m~/work/pyramid-learn/pyramid-learn/src/midlearn/_r_interface.py:239[39m, in [36m_call_r_color_theme[39m[34m(theme, **kwargs)[39m
[32m    238[39m [38;5;28;01mwith[39;00m conversion.localconverter(pandas2ri.converter + numpy2ri.converter + cv):
[32m--> [39m[32m239[39m     res = [43mmidr[49m[43m.[49m[43mcolor_theme[49m[43m([49m[43m*[49m[43m*[49m[43mr_kwargs[49m[43m)[49m
[32m    240[39m [38;5;28;01mreturn[39;00m res

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/rpy2/robjects/functions.py:208[39m, in [36mSignatureTranslatedFunction.__call__[39m[34m(self, *args, **kwargs)[39m
[32m    207[39m         kwargs[r_k] = v
[32m--> [39m[32m208[39m [38;5;28;01mreturn[39;00m ([38;5;28;43msuper[39;49m[43m([49m[43mSignatureTranslatedFunction[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[43m)[49m
[32m    209[39m [43m        [49m[43m.[49m[34;43m__call__[39;49m[43m([49m[43m*[49m[43margs[49m[43m,[49m[43m [49m[43m*[49m[43m*[49m[43mkwargs[49m[43m)[49m)

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/rpy2/robjects/functions.py:131[39m, in [36mFunction.__call__[39m[34m(self, *args, **kwargs)[39m
[32m    130[39m         new_kwargs[k] = cv.py2rpy(v)
[32m--> [39m[32m131[39m res = [38;5;28;43msuper[39;49m[43m([49m[43mFunction[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[43m)[49m[43m.[49m[34;43m__call__[39;49m[43m([49m[43m*[49m[43mnew_args[49m[43m,[49m[43m [49m[43m*[49m[43m*[49m[43mnew_kwargs[49m[43m)[49m
[32m    132[39m res = cv.rpy2py(res)

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/rpy2/rinterface_lib/conversion.py:46[39m, in [36m_cdata_res_to_rinterface.<locals>._[39m[34m(*args, **kwargs)[39m
[32m     45[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34m_[39m(*args, **kwargs):
[32m---> [39m[32m46[39m     cdata = [43mfunction[49m[43m([49m[43m*[49m[43margs[49m[43m,[49m[43m [49m[43m*[49m[43m*[49m[43mkwargs[49m[43m)[49m
[32m     47[39m     [38;5;66;03m# TODO: test cdata is of the expected CType[39;00m

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/rpy2/rinterface/__init__.py:926[39m, in [36mSexpClosure.__call__[39m[34m(self, *args, **kwargs)[39m
[32m    925[39m     [38;5;28;01mif[39;00m error_occured[[32m0[39m]:
[32m--> [39m[32m926[39m         [38;5;28;01mraise[39;00m embedded.RRuntimeError(_rinterface._geterrmessage())
[32m    927[39m [38;5;28;01mreturn[39;00m res

[31mRRuntimeError[39m: Error in get.theme(parsed$name, ifnot.null(parsed$source, source), env) : 
  'mako' is not found in the color theme environment


During handling of the above exception, another exception occurred:

[31mRExecutionError[39m                           Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[8][39m[32m, line 2[39m
[32m      1[39m [38;5;66;03m# Plot individual conditional expectations (ICE) with color encoding[39;00m
[32m----> [39m[32m2[39m [43mexplainer[49m[43m.[49m[43mconditional[49m[43m([49m[33;43m'[39;49m[33;43mLatitude[39;49m[33;43m'[39;49m[43m)[49m[43m.[49m[43mplot[49m[43m([49m[43mvar_color[49m[43m=[49m[33;43m'[39;49m[33;43mLongitude[39;49m[33;43m'[39;49m[43m,[49m[43m [49m[43mtheme[49m[43m=[49m[33;43m'[39;49m[33;43mmako[39;49m[33;43m'[39;49m[43m)[49m.draw()

[36mFile [39m[32m~/work/pyramid-learn/pyramid-learn/src/midlearn/plotting.py:269[39m, in [36mplot_conditional[39m[34m(conditional, style, theme, var_color, dots, reference, **kwargs)[39m
[32m    267[39m     p += p9.aes(color=var_color)
[32m    268[39m [38;5;28;01mif[39;00m theme [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[32m--> [39m[32m269[39m     p += [43mscale_color_theme[49m[43m([49m[43mtheme[49m[43m)[49m
[32m    270[39m [38;5;28;01mreturn[39;00m p

[36mFile [39m[32m~/work/pyramid-learn/pyramid-learn/src/midlearn/plotting_theme.py:44[39m, in [36mscale_color_theme[39m[34m(theme, midpoint, **kwargs)[39m
[32m     39[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34mscale_color_theme[39m(
[32m     40[39m     theme: [38;5;28mstr[39m | color_theme,
[32m     41[39m     midpoint: [38;5;28mfloat[39m = [32m0[39m,
[32m     42[39m     **kwargs
[32m     43[39m ) -> scale_color_theme_d | scale_color_theme_c:
[32m---> [39m[32m44[39m     theme = [43mcolor_theme[49m[43m([49m[43mtheme[49m[43m=[49m[43mtheme[49m[43m)[49m
[32m     45[39m     [38;5;28;01mif[39;00m theme.type == [33m'[39m[33mqualitative[39m[33m'[39m:
[32m     46[39m         [38;5;28;01mreturn[39;00m scale_color_theme_d(theme=theme, **kwargs)

[36mFile [39m[32m~/work/pyramid-learn/pyramid-learn/src/midlearn/plotting_theme.py:15[39m, in [36mcolor_theme.__init__[39m[34m(self, theme, **kwargs)[39m
[32m     14[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34m__init__[39m([38;5;28mself[39m, theme: [38;5;28mstr[39m | color_theme, **kwargs):
[32m---> [39m[32m15[39m     [38;5;28mself[39m._obj = [43m_r_interface[49m[43m.[49m[43m_call_r_color_theme[49m[43m([49m
[32m     16[39m [43m        [49m[43mtheme[49m[43m [49m[43m=[49m[43m [49m[43mtheme[49m[43m,[49m
[32m     17[39m [43m        [49m[43m*[49m[43m*[49m[43mkwargs[49m
[32m     18[39m [43m    [49m[43m)[49m
[32m     19[39m     [38;5;28mself[39m.name = [38;5;28mself[39m._obj[[33m'[39m[33mname[39m[33m'[39m][[32m0[39m]
[32m     20[39m     [38;5;28mself[39m.type = [38;5;28mself[39m._obj[[33m'[39m[33mtype[39m[33m'[39m][[32m0[39m]

[36mFile [39m[32m~/work/pyramid-learn/pyramid-learn/src/midlearn/_r_interface.py:242[39m, in [36m_call_r_color_theme[39m[34m(theme, **kwargs)[39m
[32m    240[39m     [38;5;28;01mreturn[39;00m res
[32m    241[39m [38;5;28;01mexcept[39;00m RRuntimeError [38;5;28;01mas[39;00m e:
[32m--> [39m[32m242[39m     [38;5;28;01mraise[39;00m RExecutionError([33mf[39m[33m"[39m[33mError in R[39m[33m'[39m[33ms midr::color_theme() function: [39m[38;5;132;01m{[39;00me[38;5;132;01m}[39;00m[33m"[39m)

[31mRExecutionError[39m: Error in R's midr::color_theme() function: Error in get.theme(parsed$name, ifnot.null(parsed$source, source), env) : 
  'mako' is not found in the color theme environment


